/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'bank_mega';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String BG_QUIZ = 'assets/gambar/bg_quiz.png';
  static const String CELEBRATION = 'assets/gambar/celebration.png';
  static const String LOGIN_FAILED = 'assets/gambar/login_failed.png';
  static const String LOGIN_TOP_SHAPE = 'assets/gambar/login_top_shape.png';
  static const String MEGA = 'assets/gambar/mega.jpg';
  static const String PRODUCT_HEALTH_INS = 'assets/gambar/product_health_ins.png';
  static const String PRODUCT_HOUSE_INS = 'assets/gambar/product_house_ins.png';
  static const String PRODUCT_TRAVEL_INS = 'assets/gambar/product_travel_ins.png';
  static const String PRODUCT_VEHICLE_INS = 'assets/gambar/product_vehicle_ins.png';
  static const String TOWN_BACKGROUND_CUTOUT = 'assets/gambar/town_background_cutout.png';
  static const String AGENCYROOM = 'assets/logo/agencyroom.png';
  static const String MEGA_INSURANCE = 'assets/logo/mega_insurance.png';
  static const String ANM_TRAVEL = 'assets/lottie/anm_travel.json';
}
