/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'bank_mega';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String BG_QUIZ = 'assets/gambar/bg_quiz.png';
  static const String BGDEPAN = 'assets/gambar/bgdepan.png';
  static const String CELEBRATION = 'assets/gambar/celebration.png';
  static const String DEFAULT = 'assets/gambar/default.jpg';
  static const String LOGIN_FAILED = 'assets/gambar/login_failed.png';
  static const String LOGIN_TOP_SHAPE = 'assets/gambar/login_top_shape.png';
  static const String LOGO = 'assets/gambar/logo.png';
  static const String MEGA = 'assets/gambar/mega.jpg';
  static const String PRODUCT_HEALTH_INS = 'assets/gambar/product_health_ins.png';
  static const String PRODUCT_HOUSE_INS = 'assets/gambar/product_house_ins.png';
  static const String PRODUCT_TRAVEL_INS = 'assets/gambar/product_travel_ins.png';
  static const String PRODUCT_VEHICLE_INS = 'assets/gambar/product_vehicle_ins.png';
  static const String TOWN_BACKGROUND_CUTOUT = 'assets/gambar/town_background_cutout.png';
  static const String AGENCYROOM = 'assets/logo/agencyroom.png';
  static const String MEGA_INSURANCE = 'assets/logo/mega_insurance.png';
  static const String ANM_ARROW = 'assets/lottie/anm_arrow.json';
  static const String ANM_ASSESS = 'assets/lottie/anm_assess.json';
  static const String ANM_BALOON = 'assets/lottie/anm_baloon.json';
  static const String ANM_BIRD = 'assets/lottie/anm_bird.json';
  static const String ANM_CELEBRATION = 'assets/lottie/anm_celebration.json';
  static const String ANM_CHART = 'assets/lottie/anm_chart.json';
  static const String ANM_CHECKMARK = 'assets/lottie/anm_checkmark.json';
  static const String ANM_CIRCLE = 'assets/lottie/anm_circle.json';
  static const String ANM_CONFIRMED = 'assets/lottie/anm_confirmed.json';
  static const String ANM_FORBIDDEN = 'assets/lottie/anm_forbidden.json';
  static const String ANM_HELPER = 'assets/lottie/anm_helper.json';
  static const String ANM_ID = 'assets/lottie/anm_id.json';
  static const String ANM_LEARNING = 'assets/lottie/anm_learning.json';
  static const String ANM_LIST = 'assets/lottie/anm_list.json';
  static const String ANM_LOADING = 'assets/lottie/anm_loading.json';
  static const String ANM_LOADING_CIRCLE = 'assets/lottie/anm_loading_circle.json';
  static const String ANM_LOGOBG = 'assets/lottie/anm_logobg.json';
  static const String ANM_OTP = 'assets/lottie/anm_otp.json';
  static const String ANM_PLANE = 'assets/lottie/anm_plane.json';
  static const String ANM_REMINDER = 'assets/lottie/anm_reminder.json';
  static const String ANM_ROCKETHIRE = 'assets/lottie/anm_rockethire.json';
  static const String ANM_ROUTE = 'assets/lottie/anm_route.json';
  static const String ANM_ROUTES = 'assets/lottie/anm_routes.json';
  static const String ANM_SALES = 'assets/lottie/anm_sales.json';
  static const String ANM_SNAIL = 'assets/lottie/anm_snail.json';
  static const String ANM_SPLASH = 'assets/lottie/anm_splash.json';
  static const String ANM_THROPHY = 'assets/lottie/anm_throphy.json';
  static const String ANM_TODO = 'assets/lottie/anm_todo.json';
  static const String ANM_TOWN = 'assets/lottie/anm_town.json';
  static const String ANM_TOWNS = 'assets/lottie/anm_towns.json';
  static const String ANM_TRAVEL = 'assets/lottie/anm_travel.json';
}
